<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>RestaurantWiFiControl</AssemblyName>
    <RootNamespace>RestaurantWiFiControl</RootNamespace>
    <Version>9.3.1</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../RestaurantWiFiStorage/RestaurantWiFiStorage.csproj" />
    <ProjectReference Include="../RestaurantWiFiNetworking/RestaurantWiFiNetworking.csproj" />
  </ItemGroup>
</Project>
